Resolving- [ tud-484 ] -Add button for reset password and 2fa
MetaSavages/admin-dashboard pull request #21
Opened 2023-10-10 07:48 UTC by Tsirov

2023-10-10 09:34 UTC, S-Hristov requested changes

2023-10-10 09:34 UTC, S-Hristov commented on src/App.js
> +        setUserDetails(dispatch, user);
remove this

2023-10-10 09:34 UTC, S-Hristov commented on src/App.js
> +  setUserDetails
remove this

2023-10-10 09:34 UTC, S-Hristov commented on src/context/index.js
> +    case 'USER_DETAILS': {
remove this

2023-10-10 09:34 UTC, S-Hristov commented on src/context/index.js
> +    userDetails: '',
remove this

2023-10-10 09:34 UTC, S-Hristov commented on src/context/index.js
> +const setUserDetails = (dispatch, value) => dispatch({ type: 'USER_DETAILS', value });
remove this

2023-10-10 09:34 UTC, S-Hristov commented on src/context/index.js
> +  setUserDetails,
remove this

2023-10-10 09:34 UTC, S-Hristov commented on src/layouts/user-management/components/UserInfo/index.js
> +  const { userDetails } = controller;
remove this

2023-10-10 09:34 UTC, S-Hristov commented on src/constants/Admin/index.js
> +export const PERMISSION_OBJECT = {
this is not a good practice since we add new permissions regularly

2023-10-10 09:34 UTC, S-Hristov commented on src/layouts/user-management/edit-user/index.js
> +                              <Tooltip title='Reset password and 2fa of the users'>
This tooltip is not neccessary as it does not add additional information to the text in the button itself

2023-10-13 06:41 UTC, Tsirov commented on src/App.js
> +        setUserDetails(dispatch, user);
I think that is bettor to heve user in one property because when we want some information aboute the user is betтer from one property to take information instead from many properties.

2023-10-13 06:42 UTC, Tsirov commented on src/layouts/user-management/edit-user/index.js
> +                              <Tooltip title='Reset password and 2fa of the users'>
Dani wanted the button to have tooltip for additional information

2023-10-13 10:31 UTC, Tsirov commented on src/constants/Admin/index.js
> +export const PERMISSION_OBJECT = {
I think that this is the better way to use it because we need to add new permission only in one plaice or if we need to change some premission name. We can use it like his 
`<Can I='update' a={PERMISSION_OBJECT.RESETPASSWORDAND2FA}>`

2023-10-13 12:19 UTC, S-Hristov commented on src/App.js
> +        setUserDetails(dispatch, user);
I believe it is easier to use multiple props as we rarely need more that 2 at once thus making it easier on the app to pass around overhead information, but even if we decide to use one variable you have not used it anywhere in your code so I suggest removing it.

2023-10-13 12:19 UTC, S-Hristov commented on src/layouts/user-management/edit-user/index.js
> +                              <Tooltip title='Reset password and 2fa of the users'>
Then change the text of the tooltip to provide additional information.

2023-11-03 15:24 UTC, merged