Resolving- [ table redirection ] -Fix table redirection to user profile
MetaSavages/admin-dashboard pull request #55
Opened 2024-01-12 08:08 UTC by Tsirov

2024-02-02 09:45 UTC, S-Hristov requested changes

2024-02-02 09:45 UTC, S-Hristov commented on src/constants/metricsType.js
> +export const MetricsType = {
This should not be constanst and should be fetched from the backend

2024-02-02 09:45 UTC, S-Hristov commented on src/data/eventHistoryColumnData.js
> +      return <MDBox sx={{ paddingRight: '20px' }}>{row.original.timestamp}</MDBox>;
Does not work on dark theme

2024-02-02 09:45 UTC, S-Hristov commented on src/layouts/player-management/components/Filters/index.js
> -        isDemo: isDemoChecked
Demo and promo code filtres do not work together adn they should be next to each other not on top of each other

2024-02-02 09:45 UTC, S-Hristov commented on src/data/codesColumnData.js
> +              isCodeClaimed
Redirect does not work

2024-02-02 09:45 UTC, S-Hristov commented on src/layouts/codes/components/Filters/index.js
> +      <Grid container spacing={2}>
This filter layout does not look good please use the old one

2024-02-02 09:45 UTC, S-Hristov commented on src/layouts/event_history/components/Filters/index.js
> +  const [isLargeScreen, setIsLargeScreen] = useState(window.innerWidth < 992);
This is not how resizing should work either use media queries or use the MUI grid sizes

2024-02-02 09:45 UTC, S-Hristov commented on src/examples/Breadcrumbs/index.js
> +        <MDBox className='aaaaaa666' sx={{ cursor: 'pointer' }} onClick={() => navigate(-1)}>
I am not sure what this classname should be but if it is required please use a readable name

2024-02-02 09:45 UTC, S-Hristov commented on src/examples/Breadcrumbs/index.js
> +          <Link className='aaaaa444' to={`/${el}`} key={el}>
I am not sure what this classname should be but if it is required please use a readable name

2024-02-02 09:45 UTC, S-Hristov commented on src/layouts/codes/components/Filters/index.js
> +            Are you sure you want to delete this all promo codes?
Should be "Are you sure you want to delete all promo codes?"

2024-02-06 08:29 UTC, Tsirov commented on src/layouts/player-management/components/Filters/index.js
> -        isDemo: isDemoChecked
Done

2024-02-06 08:37 UTC, Tsirov commented on src/data/codesColumnData.js
> +              isCodeClaimed
![image](https://github.com/MetaSavages/admin-dashboard/assets/85445723/842db401-029a-431e-9ec0-d023ad84e3eb)

it is working

2024-02-06 09:50 UTC, Tsirov commented on src/layouts/event_history/components/Filters/index.js
> +  const [isLargeScreen, setIsLargeScreen] = useState(window.innerWidth < 992);
This is about reordering component in small size in one place and after that in other place instead to add the same component on the two places (to have same code on two places with different display view)
![image](https://github.com/MetaSavages/admin-dashboard/assets/85445723/ae1b1ac4-4f61-4e1f-a5a3-6252de588261)

2024-02-06 09:55 UTC, Tsirov commented on src/constants/metricsType.js
> +export const MetricsType = {
I think that this is simple and transparent, because in this why we can see the metrics types and names. If we make this to be taken from the database then we need every time to look the property names that come from the database and in this way is difficile.

2024-02-08 09:42 UTC, merged