Resolving - [ tud-669 ] -Fix on deleting some property from table to do not need to refresh page to apply new changes
MetaSavages/admin-dashboard pull request #61
Opened 2024-03-12 12:12 UTC by Tsirov

2024-03-19 09:25 UTC, S-Hristov requested changes

2024-03-19 09:25 UTC, S-Hristov commented on src/data/permissionsColumnData.js
> +                    .then(() => {
Don't use .then use async awaut

2024-03-19 09:25 UTC, S-Hristov commented on src/data/rolesColumnData.js
> +                  searchParams.set('role-management', deleteRoleId);
Don't use .then use async awaut

2024-03-19 09:25 UTC, S-Hristov commented on src/layouts/player-management/index.js
> +  console.log('filtersssssssssssss', filters);
remove logs

2024-03-19 09:25 UTC, S-Hristov commented on src/layouts/user-management/index.js
> +                  .then(() => {
Don't use .then use async awaut

2024-03-19 09:25 UTC, S-Hristov commented on src/services/users/index.js
> +    throw new Error(err.message);
Either catch it and handle it or do not us try catch

2024-03-19 09:25 UTC, S-Hristov commented on src/services/roles/index.js
> +    throw new Error(err.message);
Either catch it and handle it or do not us try catch

2024-03-19 09:25 UTC, S-Hristov commented on src/services/players/index.js
> +    throw new Error(err.message);
Either catch it and handle it or do not us try catch

2024-03-19 09:25 UTC, S-Hristov commented on src/services/permissions/index.js
> +    throw new Error(err.message);
Either catch it and handle it or do not us try catch

2024-03-20 10:13 UTC, Tsirov commented on src/data/permissionsColumnData.js
> +                    .then(() => {
Fixed.

2024-03-20 10:14 UTC, Tsirov commented on src/data/rolesColumnData.js
> +                  searchParams.set('role-management', deleteRoleId);
Fixed.

2024-03-20 10:14 UTC, Tsirov commented on src/layouts/player-management/index.js
> +  console.log('filtersssssssssssss', filters);
Fixed.

2024-03-20 10:14 UTC, Tsirov commented on src/layouts/user-management/index.js
> +                  .then(() => {
Fixed.

2024-03-20 10:14 UTC, Tsirov commented on src/services/users/index.js
> +    throw new Error(err.message);
Fixed.

2024-03-20 10:14 UTC, Tsirov commented on src/services/roles/index.js
> +    throw new Error(err.message);
Fixed.

2024-03-20 10:14 UTC, Tsirov commented on src/services/players/index.js
> +    throw new Error(err.message);
Fixed.

2024-03-20 10:14 UTC, Tsirov commented on src/services/permissions/index.js
> +    throw new Error(err.message);
Fixed.

2024-03-22 14:31 UTC, merged