Fix/support
MetaSavages/admin-dashboard pull request #62
Opened 2024-03-15 14:12 UTC by SamBorisov

Show live data when we reply, we need to refresh the page now

Need to take a ticket before replying and being able to write (so no multiple admins type a reply at the same time)

Not ‘Close ticket’ -> ‘End Ticket’ ->Could be easily mistaken, also should be with a different color

Long messages for ticket descriptions are not showing well

Re-take possibility (steal ticket)

Make it look better

View button, not “view & reply”

Filter by taken, by your taken tickets, and by subject

Search option - nice to have

Show to who is assigned (by who is taken) when we view it!

On the right is you, and on the left is the player on the chat - better visual

2024-03-19 09:34 UTC, S-Hristov requested changes

2024-03-19 09:34 UTC, S-Hristov commented on src/services/support/index.js
> +    throw new Error(err.message);
Either use try catch and handle the exception or just let the error fire it is unnecessary to catch an error and throw it agait

2024-03-19 09:34 UTC, S-Hristov commented on src/services/support/index.js
> +    throw new Error(err.message);
Either use try catch and handle the exception or just let the error fire it is unnecessary to catch an error and throw it agait

2024-03-19 09:34 UTC, S-Hristov commented on src/services/support/index.js
> +    throw new Error(err.message);
Either use try catch and handle the exception or just let the error fire it is unnecessary to catch an error and throw it agait

2024-03-19 09:34 UTC, S-Hristov commented on src/services/support/index.js
> +    throw new Error(err.message);
Either use try catch and handle the exception or just let the error fire it is unnecessary to catch an error and throw it agait

2024-03-19 09:34 UTC, S-Hristov commented on src/services/support/index.js
> +    throw new Error(err.message);
Either use try catch and handle the exception or just let the error fire it is unnecessary to catch an error and throw it agait

2024-03-19 09:34 UTC, S-Hristov commented on src/services/support/index.js
> +    if (Object.keys(filters).length) {
Whati s the point of using this just rename the parameters to match the expected payload and let the backend handle it.

2024-03-19 13:02 UTC, SamBorisov commented on src/services/support/index.js
> +    if (Object.keys(filters).length) {
Made filters with the same name

2024-03-20 09:55 UTC, SamBorisov commented on src/services/support/index.js
> +    throw new Error(err.message);
no not using try-catch in both service and when we call the function

2024-03-20 09:55 UTC, SamBorisov commented on src/services/support/index.js
> +    throw new Error(err.message);
no not using try-catch in both service and when we call the function

2024-03-20 09:55 UTC, SamBorisov commented on src/services/support/index.js
> +    throw new Error(err.message);
no not using try-catch in both service and when we call the function

2024-03-20 09:55 UTC, SamBorisov commented on src/services/support/index.js
> +    throw new Error(err.message);
no not using try-catch in both service and when we call the function

2024-03-20 09:56 UTC, SamBorisov commented on src/services/support/index.js
> +    throw new Error(err.message);
no not using try-catch in both service and when we call the function

2024-03-22 14:30 UTC, merged